SOURCE: SynthiaSeq
DATA_DIRECTORY_SOURCE: ../../video_seg/TPS/data/SynthiaSeq/SEQS-04-DAWN
DATA_LIST_SOURCE: tps/dataset/SynthiaSeq_list/train.txt
NUM_CLASSES: 12
generate_threshold_path: experiments_result/generate_synthina

TRAIN:
  LEARNING_RATE: 0.00025
  EARLY_STOP: 40000
  LAMBDA_T: 1.0
  
  SCALING_RATIO:
    - 0.8
    - 1.2
  flow_path_src: ../../video_seg/TPS/tps/data/estimated_optical_flow_synthiaseq_train
  DA_METHOD: TPS
  INFO_TARGET: tps/dataset/CityscapesSeq_list/info_SynthiaSeq.json
  SET_SOURCE: train
  INPUT_SIZE_SOURCE:
    - 1280
    - 640
  SAVE_PRED_EVERY: 100
  SNAPSHOT_DIR_ACC_1: experiments_result/snapshots/tps_syn2city_ACC_1
  SNAPSHOT_DIR_ACC_2: experiments_result/snapshots/tps_syn2city_ACC_2
  SNAPSHOT_DIR_ACC_3: experiments_result/snapshots/tps_syn2city_ACC_3
  SNAPSHOT_DIR_ACC_4: experiments_result/snapshots/tps_syn2city_ACC_4
  SNAPSHOT_DIR_ACC_5: experiments_result/snapshots/tps_syn2city_ACC_5
  SNAPSHOT_DIR_ACC_6: experiments_result/snapshots/tps_syn2city_ACC_6
  SNAPSHOT_DIR_ACC_7: experiments_result/snapshots/tps_syn2city_ACC_7
  SNAPSHOT_DIR_ACC_8: experiments_result/snapshots/tps_syn2city_ACC_8
  SNAPSHOT_DIR_ACC_9: experiments_result/snapshots/tps_syn2city_ACC_9
  
  SNAPSHOT_DIR_TCSM_1: experiments_result/snapshots/tps_syn2city_TCSM_1
  SNAPSHOT_DIR_TCSM_2: experiments_result/snapshots/tps_syn2city_TCSM_2
  SNAPSHOT_DIR_TCSM_3: experiments_result/snapshots/tps_syn2city_TCSM_3
  SNAPSHOT_DIR_TCSM_4: experiments_result/snapshots/tps_syn2city_TCSM_4
  SNAPSHOT_DIR_TCSM_5: experiments_result/snapshots/tps_syn2city_TCSM_5
  SNAPSHOT_DIR_TCSM_6: experiments_result/snapshots/tps_syn2city_TCSM_6
  SNAPSHOT_DIR_TCSM_7: experiments_result/snapshots/tps_syn2city_TCSM_7
  SNAPSHOT_DIR_TCSM_8: experiments_result/snapshots/tps_syn2city_TCSM_8
  SNAPSHOT_DIR_TCSM_9: experiments_result/snapshots/tps_syn2city_TCSM_9

  RESTORE_FROM_ACC0 : 'pretrained_models/DeepLab_resnet_pretrained_imagenet.pth'
  RESTORE_FROM_ACC1 : 'trained_models/SYN/RESTORE_FROM_ACC1.pth' # the best model in SNAPSHOT_DIR_ACC_1
  RESTORE_FROM_ACC2 : 'trained_models/SYN/RESTORE_FROM_ACC2.pth'
  RESTORE_FROM_ACC3 : 'trained_models/SYN/RESTORE_FROM_ACC3.pth'

  RESTORE_FROM_TCSM0 : 'pretrained_models/DeepLab_resnet_pretrained_imagenet.pth'
  RESTORE_FROM_TCSM1 : 'trained_models/SYN/RESTORE_FROM_TCSM1.pth'
  RESTORE_FROM_TCSM2 : 'trained_models/SYN/RESTORE_FROM_TCSM2.pth'
  RESTORE_FROM_TCSM3 : 'trained_models/SYN/RESTORE_FROM_TCSM3.pth'

  TENSORBOARD_LOGDIR1 : 'experiments_result/tensorboard/syn2city_TPS/acc1'
  TENSORBOARD_LOGDIR2 : 'experiments_result/tensorboard/syn2city_TPS/acc2'
  TENSORBOARD_LOGDIR3 : 'experiments_result/tensorboard/syn2city_TPS/acc3'
  TENSORBOARD_LOGDIR4 : 'experiments_result/tensorboard/syn2city_TPS/acc4'
  TENSORBOARD_LOGDIR5 : 'experiments_result/tensorboard/syn2city_TPS/acc5'
  TENSORBOARD_LOGDIR6 : 'experiments_result/tensorboard/syn2city_TPS/acc6'
  TENSORBOARD_LOGDIR7 : 'experiments_result/tensorboard/syn2city_TPS/acc7'
  TENSORBOARD_LOGDIR8 : 'experiments_result/tensorboard/syn2city_TPS/acc8'
  TENSORBOARD_LOGDIR9 : 'experiments_result/tensorboard/syn2city_TPS/acc9'

  TENSORBOARD_LOGDIR_TCSM1 : 'experiments_result/tensorboard/syn2city_TPS/tcsm1'
  TENSORBOARD_LOGDIR_TCSM2 : 'experiments_result/tensorboard/syn2city_TPS/tcsm2'
  TENSORBOARD_LOGDIR_TCSM3 : 'experiments_result/tensorboard/syn2city_TPS/tcsm3'
  TENSORBOARD_LOGDIR_TCSM4 : 'experiments_result/tensorboard/syn2city_TPS/tcsm4'
  TENSORBOARD_LOGDIR_TCSM5 : 'experiments_result/tensorboard/syn2city_TPS/tcsm5'
  TENSORBOARD_LOGDIR_TCSM6 : 'experiments_result/tensorboard/syn2city_TPS/tcsm6'
  TENSORBOARD_LOGDIR_TCSM7 : 'experiments_result/tensorboard/syn2city_TPS/tcsm7'
  TENSORBOARD_LOGDIR_TCSM8 : 'experiments_result/tensorboard/syn2city_TPS/tcsm8'
  TENSORBOARD_LOGDIR_TCSM9 : 'experiments_result/tensorboard/syn2city_TPS/tcsm9'
TEST:
  SNAPSHOT_DIR_ACC_1: ['experiments_result/snapshots/tps_syn2city_ACC_1']
  SNAPSHOT_DIR_ACC_2: ['experiments_result/snapshots/tps_syn2city_ACC_2']
  SNAPSHOT_DIR_ACC_3: ['experiments_result/snapshots/tps_syn2city_ACC_3']
  SNAPSHOT_DIR_ACC_4: ['experiments_result/snapshots/tps_syn2city_ACC_4']
  SNAPSHOT_DIR_ACC_5: ['experiments_result/snapshots/tps_syn2city_ACC_5']
  SNAPSHOT_DIR_ACC_6: ['experiments_result/snapshots/tps_syn2city_ACC_6']
  SNAPSHOT_DIR_ACC_7: ['experiments_result/snapshots/tps_syn2city_ACC_7']
  SNAPSHOT_DIR_ACC_8: ['experiments_result/snapshots/tps_syn2city_ACC_8']
  SNAPSHOT_DIR_ACC_9: ['experiments_result/snapshots/tps_syn2city_ACC_9']

  SNAPSHOT_DIR_TCSM_1: ['experiments_result/snapshots/tps_syn2city_TCSM_1']
  SNAPSHOT_DIR_TCSM_2: ['experiments_result/snapshots/tps_syn2city_TCSM_2']
  SNAPSHOT_DIR_TCSM_3: ['experiments_result/snapshots/tps_syn2city_TCSM_3']
  SNAPSHOT_DIR_TCSM_4: ['experiments_result/snapshots/tps_syn2city_TCSM_4']
  SNAPSHOT_DIR_TCSM_5: ['experiments_result/snapshots/tps_syn2city_TCSM_5']
  SNAPSHOT_DIR_TCSM_6: ['experiments_result/snapshots/tps_syn2city_TCSM_6']
  SNAPSHOT_DIR_TCSM_7: ['experiments_result/snapshots/tps_syn2city_TCSM_7']
  SNAPSHOT_DIR_TCSM_8: ['experiments_result/snapshots/tps_syn2city_TCSM_8']
  SNAPSHOT_DIR_TCSM_9: ['experiments_result/snapshots/tps_syn2city_TCSM_9']



  RESTORE_FROM_ACC0 : ['../pretrained_models/DeepLab_resnet_pretrained_imagenet.pth']
  RESTORE_FROM_ACC1 : ['../trained_models/SYN/RESTORE_FROM_ACC1.pth'] # the best model in SNAPSHOT_DIR_ACC_1
  RESTORE_FROM_ACC2 : ['../trained_models/SYN/RESTORE_FROM_ACC2.pth']
  RESTORE_FROM_ACC3 : ['../trained_models/SYN/RESTORE_FROM_ACC3.pth']

  RESTORE_FROM_TCSM0 : ['../pretrained_models/DeepLab_resnet_pretrained_imagenet.pth']
  RESTORE_FROM_TCSM1 : ['../trained_models/SYN/RESTORE_FROM_TCSM1.pth']
  RESTORE_FROM_TCSM2 : ['../trained_models/SYN/RESTORE_FROM_TCSM2.pth']
  RESTORE_FROM_TCSM3 : ['../trained_models/SYN/RESTORE_FROM_TCSM3.pth']

  MODE: video_best # {'video_single', 'video_best', 'video_best_tcsm'}
  INFO_TARGET: tps/dataset/CityscapesSeq_list/info_SynthiaSeq.json
  SNAPSHOT_STEP: 100
  SNAPSHOT_START_ITER: 100
